import { useEffect, useRef, useState } from 'react';
import { useApp, useT, useLocale } from '../../core/store.js';
import { api } from '../../core/api.js';
import { teacherById } from '../../data/teachers.js';
import { tts } from '../../audio/tts.js';
import { sfx } from '../../audio/sfx.js';
import { Stat } from '../../ui/kit.jsx';
import { EXAMS, BANKS, objectiveItems, buildMock, estimate } from '../../data/exams.js';
import { useAI } from '../../ai/useAI.js';

const SEC_ICON = { reading: '📖', listening: '🎧', use: '🔤', writing: '✍️', speaking: '🎤' };
export default function ExamCenter() {
  const { user } = useApp(); const t = useT(); const locale = useLocale(); const teacher = teacherById(user.teacherId); const ai = useAI();
  const [examId, setExamId] = useState('ielts'); const [view, setView] = useState('menu'); const [items, setItems] = useState([]); const [idx, setIdx] = useState(0); const [correct, setCorrect] = useState(0); const [locked, setLocked] = useState(false); const [isMock, setIsMock] = useState(false); const [time, setTime] = useState(0); const [result, setResult] = useState(null); const timer = useRef(null); const finishedRef = useRef(false); const timedOutRef = useRef(false); const itemsRef = useRef([]); const correctRef = useRef(0); const isMockRef = useRef(false); const exam = EXAMS[examId];
  useEffect(() => () => clearInterval(timer.current), []);
  const startSection = (section) => { if (section === 'writing') { setView('writing'); return; } if (section === 'speaking') { setView('speaking'); return; } const list = objectiveItems(section); if (!list.length) return; sfx.click(); itemsRef.current = list; correctRef.current = 0; isMockRef.current = false; finishedRef.current = false; setItems(list); setIdx(0); setCorrect(0); setLocked(false); setIsMock(false); setView('run'); };
  const startMock = () => { sfx.click(); const list = buildMock(20); itemsRef.current = list; correctRef.current = 0; isMockRef.current = true; finishedRef.current = false; timedOutRef.current = false; setItems(list); setIdx(0); setCorrect(0); setLocked(false); setIsMock(true); setView('run'); setTime(1200); clearInterval(timer.current); timer.current = setInterval(() => setTime((value) => { if (value <= 1) { clearInterval(timer.current); if (!timedOutRef.current) { timedOutRef.current = true; finish(0, true); } return 0; } return value - 1; }), 1000); };
  const cur = items[idx];
  const answer = async (opt) => { if (locked) return; setLocked(true); const ok = opt === cur.answer; if (ok) { correctRef.current += 1; setCorrect((value) => value + 1); sfx.correct?.(); } else sfx.wrong?.(); api.addAttempt({ taskType: 'exam', topic: examId, level: user.level, correct: ok, durationMs: 0 }).catch(() => {}); setTimeout(() => { if (idx + 1 >= items.length) finish(ok ? 1 : 0); else { setIdx(idx + 1); setLocked(false); } }, 700); };
  const finish = (lastDelta = 0, timeUp = false) => { if (finishedRef.current) return; finishedRef.current = true; clearInterval(timer.current); const sourceItems = timeUp ? itemsRef.current : items; const total = sourceItems.length || 1; const finalCorrect = Math.min(total, timeUp ? correctRef.current : correct + lastDelta); const acc = finalCorrect / total; const mock = timeUp ? isMockRef.current : isMock; if (mock) { const est = estimate(examId, acc), xp = Math.round(acc * 120), coins = Math.round(acc * 60); api.earn({ xp, coins }).catch(() => {}); setResult({ acc, correct: finalCorrect, total, est, xp, coins, timeUp }); sfx.levelUp?.(); } else setResult({ acc, correct: finalCorrect, total, est: null }); setView('result'); };
  if (view === 'menu') return <div className="space-y-5"><div><h1 className="h1">📝 {t('exam.title')}</h1><p className="font-semibold text-ink/55 mt-1">{t('exam.subtitle')}</p></div><div className="flex gap-2">{Object.values(EXAMS).map((e) => <button key={e.id} onClick={() => { sfx.click(); setExamId(e.id); }} className={`btn !py-2 ${examId === e.id ? 'btn-primary' : 'btn-ghost'}`}>{e.name}</button>)}</div><div className="card p-4 flex items-center gap-3"><span className="text-2xl">🎓</span><div><div className="font-black">{exam.name} · <span className="text-ink/60">{exam.scale}</span></div><div className="text-xs font-semibold text-ink/50">{t('exam.note')}</div></div></div><div className="grid grid-cols-2 md:grid-cols-3 gap-3">{exam.sections.map((section) => <button key={section} onClick={() => startSection(section)} className="card p-4 text-left hover:-translate-y-1 transition"><div className="text-2xl">{SEC_ICON[section]}</div><div className="font-black mt-1">{t('exam.sec.' + section)}</div><div className="text-xs font-semibold text-ink/45">{t('exam.practice')}</div></button>)}</div><button onClick={startMock} className="btn-primary w-full !py-3">🎯 {t('exam.mock')} · {exam.scale}</button></div>;
  if (view === 'run' && cur) return <div className="max-w-2xl mx-auto"><div className="flex items-center justify-between mb-3"><span className="chip">{exam.name}{isMock ? ' · ' + t('exam.mock') : ''}</span><span className="font-black text-sm">{idx + 1} / {items.length}{isMock ? ` · ⏱ ${String(Math.floor(time / 60)).padStart(1, '0')}:${String(time % 60).padStart(2, '0')}` : ''}</span></div>{cur.passage && <div className="card p-4 mb-3 text-sm font-semibold leading-relaxed">{cur.passage}</div>}{cur.transcript && <div className="card p-4 mb-3 flex items-center gap-3"><button className="btn-primary !py-2" onClick={() => tts.speak(cur.transcript, teacher)}>▶ {t('exam.play')}</button><span className="text-xs font-semibold text-ink/45">{t('exam.listenHint')}</span></div>}<div className="card p-5"><div className="font-black text-lg mb-4">{cur.q}</div><div className="grid gap-2">{cur.options.map((option) => <button key={option} disabled={locked} onClick={() => answer(option)} className={`btn-ghost !justify-start text-left ${locked && option === cur.answer ? '!bg-emerald-100 !text-emerald-700' : ''}`}>{option}</button>)}</div></div></div>;
  if (view === 'writing') return <Writing examId={examId} t={t} locale={locale} level={user.level} runAI={ai.runTask} onBack={() => setView('menu')} />;
  if (view === 'speaking') return <Speaking examId={examId} t={t} teacher={teacher} onBack={() => setView('menu')} />;
  if (view === 'result') return <div className="max-w-lg mx-auto text-center card p-8"><div className="text-5xl">{result.acc >= 0.7 ? '🏆' : result.acc >= 0.5 ? '🎉' : '💪'}</div>{result.est ? <><h2 className="h1 mt-3">{result.est.headline}</h2><p className="font-bold text-ink/60">CEFR ≈ {result.est.cefr}</p></> : <h2 className="h2 mt-3">{result.correct} / {result.total}</h2>}<div className="grid grid-cols-3 gap-2 my-5"><Stat icon="✅" label={t('exam.correct')} value={`${result.correct}/${result.total}`} /><Stat icon="🎯" label={t('home.accuracy')} value={Math.round(result.acc * 100) + '%'} />{result.est && <Stat icon="⭐" label="XP" value={'+' + result.xp} />}</div><p className="text-xs font-semibold text-ink/45 mb-4">{t('exam.note')}</p><button className="btn-primary w-full" onClick={() => setView('menu')}>↩ {t('exam.back')}</button></div>;
  return <div className="font-bold text-ink/40">{t('common.loading')}</div>;
}

function Writing({ examId, t, locale, level, runAI, onBack }) {
  const prompts = BANKS.WRITING[examId], [pi, setPi] = useState(0), [text, setText] = useState(''), [grade, setGrade] = useState(null), [grading, setGrading] = useState(false); const p = prompts[pi]; const words = text.trim() ? text.trim().split(/\s+/).length : 0; const ok = words >= p.minWords;
  const submit = async () => { if (!text.trim()) return; setGrading(true); const output = await runAI('grade_writing', { text, prompt: p.task, minWords: p.minWords, examId }, { locale, level }); setGrade(output); setGrading(false); };
  return <div className="max-w-2xl mx-auto space-y-4"><button className="btn-ghost !py-1.5 text-sm" onClick={onBack}>← {t('exam.back')}</button><h1 className="h2">✍️ {t('exam.sec.writing')} · {examId.toUpperCase()}</h1><div className="flex gap-2">{prompts.map((_, i) => <button key={i} onClick={() => { setPi(i); setText(''); setGrade(null); }} className={`chip cursor-pointer ${i === pi ? '!bg-primary text-white' : ''}`}>#{i + 1}</button>)}</div><div className="card p-4 font-semibold">{p.task}</div><textarea className="input min-h-[220px]" placeholder={t('exam.writePlaceholder')} value={text} onChange={(e) => { setText(e.target.value); setGrade(null); }} /><div className="flex items-center justify-between text-sm font-bold"><span className={ok ? 'text-emerald-600' : 'text-ink/50'}>{words} / {p.minWords} {t('exam.words')} {ok ? '✅' : ''}</span><button className="btn-primary !py-2" onClick={submit} disabled={!text.trim() || grading}>{grading ? '…' : t('task.check')}</button></div>{grade && <div className="card p-5 space-y-3"><div className="flex items-center justify-between"><div className="label">{grade.source === 'fallback' ? '📏 Basic estimate' : '🤖 Local AI estimate'}</div><strong className="text-xl">{grade.data.overall}</strong></div><div className="grid grid-cols-4 gap-2">{Object.entries(grade.data.criteria).map(([key, value]) => <div key={key} className="rounded-xl bg-ink/5 p-2 text-center"><div className="font-black">{key}</div><div className="text-lg font-black">{value}</div></div>)}</div><ul className="list-disc pl-5 text-sm font-semibold space-y-1">{grade.data.feedback.map((item, i) => <li key={i}>{item}</li>)}</ul><div><div className="label mb-1">Improved version</div><p className="text-sm font-semibold leading-relaxed">{grade.data.improved}</p></div></div>}<div className="card p-4"><div className="label mb-2">{t('exam.rubric')}</div><ul className="text-sm font-semibold text-ink/70 space-y-1 list-disc pl-5"><li>{t('exam.r1')}</li><li>{t('exam.r2')}</li><li>{t('exam.r3')}</li><li>{t('exam.r4')}</li></ul></div></div>;
}
function Speaking({ examId, t, teacher, onBack }) { const prompts = BANKS.SPEAKING[examId], [pi, setPi] = useState(0); return <div className="max-w-2xl mx-auto space-y-4"><button className="btn-ghost !py-1.5 text-sm" onClick={onBack}>← {t('exam.back')}</button><h1 className="h2">🎤 {t('exam.sec.speaking')} · {examId.toUpperCase()}</h1><div className="flex gap-2">{prompts.map((_, i) => <button key={i} onClick={() => setPi(i)} className={`chip cursor-pointer ${i === pi ? '!bg-primary text-white' : ''}`}>#{i + 1}</button>)}</div><div className="card p-5 font-semibold text-lg">{prompts[pi]}</div><button className="btn-primary" onClick={() => tts.speak(prompts[pi], teacher)}>▶ {t('exam.play')}</button><p className="text-sm font-semibold text-ink/50">{t('exam.speakHint')}</p></div>; }
